version: '3.7'
services:
 backend-dev:
  build:
   context: backend
   dockerfile: development.dockerfile
  working_dir: /src
  volumes:
   - .:/src
   - ./docker-compose-dev/dev-certificates/root-ca.pem:/euler/root-ca.pem:ro
  user: ${CURRENT_UID}:${CURRENT_GID}
  environment:
   - LANG=C.UTF-8
   - LC_ALL=C.UTF-8
   - CONFIG_FILE=/src/docker-compose-dev/backend.conf
  ports:
   - 8000:8000
  depends_on:
   - elastic-dev
  command: /src/docker-compose-dev/backend-entrypoint.sh
  depends_on:
   - generate-certificates
 elastic-dev:
  image: amazon/opendistro-for-elasticsearch:1.9.0
  environment:
   discovery.type: single-node
  ports:
   - 9200:9200
   - 9600:9600
  volumes:
   - {{ cookiecutter.project_slug }}-es-data-dev:/usr/share/elasticsearch/data
   - ./docker-compose-dev/opendistro-config.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml:ro
   - ./docker-compose-dev/opendistro-internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml:ro
   - ./docker-compose-dev/opendistro-roles.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles.yml:ro
   - ./docker-compose-dev/opendistro-roles_mapping.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles_mapping.yml:ro
   - ./docker-compose-dev/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
   - ./docker-compose-dev/dev-certificates/euler.pem:/usr/share/elasticsearch/config/euler.pem:ro
   - ./docker-compose-dev/dev-certificates/euler-key.pem:/usr/share/elasticsearch/config/euler-key.pem:ro
   - ./docker-compose-dev/dev-certificates/elastic-dev.pem:/usr/share/elasticsearch/config/node.pem:ro
   - ./docker-compose-dev/dev-certificates/elastic-dev-key.pem:/usr/share/elasticsearch/config//node-key.pem:ro
   - ./docker-compose-dev/dev-certificates/root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem:ro
  depends_on:
   - generate-certificates
 kibana-dev:
  image: amazon/opendistro-for-elasticsearch-kibana:1.9.0
  ports:
   - 5601:5601
  environment:
   ELASTICSEARCH_URL: https://elastic-dev:9200
   ELASTICSEARCH_HOSTS: https://elastic-dev:9200
  volumes:
   - ./docker-compose-dev/dev-certificates/root-ca.pem:/usr/share/kibana/config/root-ca.pem:ro
  depends_on:
   - elastic-dev
   - generate-certificates
 generate-certificates:
  build:
   context: docker-compose-dev
   dockerfile: generate-certificates.dockerfile
  working_dir: /certificates
  user: ${CURRENT_UID}:${CURRENT_GID}
  environment:
    OUTPUT: /certificates/dev-certificates
  volumes:
   - ./docker-compose-dev:/certificates
volumes:
 {{ cookiecutter.project_slug }}-es-data-dev:
