version: '3.7'
services:
 backend-dev:
  build:
   context: backend
   dockerfile: development.dockerfile
  working_dir: /src
  volumes:
   - .:/src
   - ./development/certificates/root-ca.pem:/euler/root-ca.pem:ro
  user: ${CURRENT_UID}:${CURRENT_GID}
  environment:
   - LANG=C.UTF-8
   - LC_ALL=C.UTF-8
   - CONFIG_FILE=/src/development/backend.conf
  ports:
   - 8000:8000
  depends_on:
   - elastic-dev
  command: /src/development/backend-entrypoint.sh
 frontend-dev:
  build:
   context: frontend
   dockerfile: development.dockerfile
  working_dir: /src/frontend
  user: ${CURRENT_UID}:${CURRENT_GID}
  command:
   - /src/development/frontend-entrypoint.sh
  volumes:
   - .:/src
  ports:
   - 3000:3000
  environment:
   PORT: 3000
   REACT_APP_BASE_API_URL: "http://localhost:8000"
   WORKING_DIR: "/src/frontend"
 elastic-dev:
  image: amazon/opendistro-for-elasticsearch:1.9.0
  environment:
   discovery.type: single-node
  ports:
   - 9200:9200
   - 9600:9600
  volumes:
   - base-project-es-data-dev:/usr/share/elasticsearch/data
   - ./development/opendistro-config.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml:ro
   - ./development/opendistro-internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml:ro
   - ./development/opendistro-roles.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles.yml:ro
   - ./development/opendistro-roles_mapping.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles_mapping.yml:ro
   - ./development/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
   - ./development/certificates/euler.pem:/usr/share/elasticsearch/config/euler.pem:ro
   - ./development/certificates/euler-key.pem:/usr/share/elasticsearch/config/euler-key.pem:ro
   - ./development/certificates/elastic-dev.pem:/usr/share/elasticsearch/config/node.pem:ro
   - ./development/certificates/elastic-dev-key.pem:/usr/share/elasticsearch/config//node-key.pem:ro
   - ./development/certificates/root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem:ro
 kibana-dev:
  image: amazon/opendistro-for-elasticsearch-kibana:1.9.0
  ports:
   - 5601:5601
  environment:
   ELASTICSEARCH_URL: https://elastic-dev:9200
   ELASTICSEARCH_HOSTS: https://elastic-dev:9200
  volumes:
   - ./development/certificates/root-ca.pem:/usr/share/kibana/config/root-ca.pem:ro
  depends_on:
   - elastic-dev
 euler-dev:
  image: eulerio/euler-api-opendistro-extended:0.6.1
  ports:
   - 8080:8080
  environment:
   JAVA_OPTS: "-Dconfig.file=/euler/euler.conf"
  volumes:
   - ~:/user-home:ro
   - ./development/certificates/root-ca.pem:/euler/root-ca.pem:ro
   - ./development/euler.conf:/euler/euler.conf:ro
   
volumes:
 base-project-es-data-dev:
